
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module L4_P5(

	//////////// SEG7 //////////
	output [6:0]HEX0,
	output [6:0]HEX1,
	output [6:0]HEX2
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire on, off;
	assign on = 8'b0;
	assign off = 5'b0;


//=======================================================
//  Structural coding
//=======================================================
	assign HEX2[0] = off;
	assign HEX2[1] = on;
	assign HEX2[2] = on;
	assign HEX2[3] = on;
	assign HEX2[4] = on;
	assign HEX2[5] = off;
	assign HEX2[6] = on;
	
	assign HEX1[0] = on;
	assign HEX1[1] = off;
	assign HEX1[2] = off;
	assign HEX1[3] = on;
	assign HEX1[4] = on;
	assign HEX1[5] = on;
	assign HEX1[6] = on;
	
	assign HEX0[0] = on;
	assign HEX0[1] = on;
	assign HEX0[2] = on;
	assign HEX0[3] = on;
	assign HEX0[4] = on;
	assign HEX0[5] = on;
	assign HEX0[6] = off;

endmodule
