
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab5_Extra(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	//output		     [6:0]		HEX3,
	//output		     [6:0]		HEX4,
	//output		     [6:0]		HEX5,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [1:0]M0;


//=======================================================
//  Structural coding
//=======================================================

	mux_2bit_3to1 U0 (SW[9:8], SW[5:4], SW[3:2], SW[1:0], M0);
	char_7seg H0 (M0, HEX0);

endmodule

module mux_2bit_3to1 (S, U, V, W, M);
	input [1:0] S, U, V, W;
	output [1:0] M;
	
	assign M[0] = (~S[1] & ~S[0] & U[0]) | (~S[1] & S[0] & V[0]) | (S[1] & ~S[0] & W[0]);
	assign M[1] = (~S[1] & ~S[0] & U[1]) | (~S[1] & S[0] & V[1]) | (S[1] & ~S[0] & W[1]);
	
endmodule

module char_7seg(C, Display);
	input [1:0] C;
	output [0:6] Display;
	
	always @(posedge C)
	begin
		case(C)
			4'd0: Display <= 8'b10000001; // d
			4'd1: Display <= 8'b10000110; // E
			4'd2: Display <= 8'b11000000; // 0
			default: Display <= 8'b11111111;
		endcase
	end
	
endmodule
