
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab6(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// SEG7 //////////
	//output		     [6:0]		HEX0,
	//output		     [6:0]		HEX1,
	//output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	wire [3:0] ones;
	wire [3:0] tens;
	wire [3:0] hundreds;

//=======================================================
//  Structural coding
//=======================================================

	binary_to_bcd(SW[9:2], ones, tens, hundreds[1:0]);
	assign hundreds[3:2] = 2'b00;
	decoder_7_seg(CLOCK_50, hundreds[3:0], HEX5[6:0]);
	decoder_7_seg(CLOCK_50, tens[3:0], HEX4[6:0]);
	decoder_7_seg(CLOCK_50, ones[3:0], HEX3[6:0]);

endmodule
